name: build
on:
  push:
    tags:
      - '*'
# on:
#   push:
#     branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-11, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    # Used to host cibuildwheel
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install Cython
        python -m cython bitpack.pyx

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.1.3

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_SKIP: pp*
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2

    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
